# Generated by Django 4.1.7 on 2023-06-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question text')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_asnwer', models.BooleanField(default=False, verbose_name='Is it the correct answer?')),
                ('text', models.TextField(verbose_name='Answer text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Quiz.question')),
            ],
        ),
    ]
